[package]
name = "rustlib"
version = "0.1.0"
authors = ["Aston <astonbitecode@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
j4rs = {path = "../../j4rs/rust"}
j4rs_derive = "0.1"
serde = { version = "1.0", features = ["derive"] }