[package]
name = "rustlib"
version = "0.1.0"
authors = ["Aston <astonbitecode@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
j4rs = { git = "https://github.com/astonbitecode/j4rs.git" }
j4rs_derive = { git = "https://github.com/astonbitecode/j4rs.git" }